In [2]:
from __future__ import print_function
import torch
x = torch.rand(5, 3)
print(x)

tensor([[0.7104, 0.3108, 0.8384],
        [0.0649, 0.5779, 0.4866],
        [0.4025, 0.4698, 0.8738],
        [0.7071, 0.4375, 0.8726],
        [0.0314, 0.2600, 0.8821]])


In [4]:
x = torch.empty(5, 3)
print(x)

tensor([[9.6429e-39, 9.2755e-39, 9.1837e-39],
        [9.3674e-39, 1.0745e-38, 1.0653e-38],
        [9.5510e-39, 1.0561e-38, 1.0194e-38],
        [1.1112e-38, 1.0561e-38, 9.9184e-39],
        [1.0653e-38, 4.1327e-39, 1.0194e-38]])


In [5]:
tensor1 = torch.tensor([5.5, 3])
print(tensor1)

tensor([5.5000, 3.0000])
